### ISSUE TITLE
[Feauture Request] Key to activate the default command

### ISSUE THREAD

**Issue by Cletip** [Overdr0ne/holymotion#2]
Hi!
I think I have an idea, but I don't know if it is possible:
make a key / command that would, if called before an holymotion command :
- call the holymotion-X commmand, where X is the name of the default function
- otherwise, activate the basic command, X

I had thought of using the universal argument, and making functions like this: 
(defun holymotion-next-line-only-with-universal-argument ()
      "DOCSTRING here"
      (interactive)
      (if current-prefix-arg
          (holymotion-next-line)
        (next-line)))

The problem is that the universal argument is given after the function (here, next-line), or at least I think it is given (according to my tests).

Anyway, I think you'd have to change the basic macro to be able to integrate this feature.
What do you think about it ?

**Comment by Overdr0ne** [comment]
Yeah, a universal argument sounds like what you want. And creating a wrapper like you did I think is the right way to do that. But maybe I can build that into the macro for defining a holymotion... Yeah, I'm making a note of that, I really like it. Thanks Cletip!

And you probably know, but you can also just create a keymap, like `+next-line-keymap`, and then add as many variations as you like later, but then you don't get that comfy one-character default.

But yeah, I'll get back to you with that new feature soon.

**Comment by Overdr0ne** [comment]
Looking at this again, I think what you really want is just a prefix map:
https://www.gnu.org/software/emacs/manual/html_node/elisp/Prefix-Keys.html

I actually had already created an empty prefix keymap for just this reason called `holymotion-map`. So you would just bind your prefix key to the `holymotion-map`, then bind your holymotions within that keymap, probably just to their normal keys, so, keeping `C-n` to next line within that map.

Prefix arguments (https://www.gnu.org/software/emacs/manual/html_node/elisp/Prefix-Command-Arguments.html) I think are more suited for when you have numerical variations of a command, like with vim's motions, which might be fun to recreate one of these days now that I think of it...

**Comment by Cletip** [comment]
No no x) I definitely don't want a prefix key. I want to keep my keys where they are! Imagine that I use a command that is hyper frequently accessible in one keystrokes and that I want to make a holymotion version: 1. I will have to type two keystrokes instead of one each time to get the basic or holymotion version, and 2, This is going to involve a keystroke that is likely to be heavily used, which may not be what I want.

In my case, I just want to be able to do this: 
To be able to choose between the basic version and the holymotion version of a command with a single keystroke. Keystroke that i can choose !

I think finally I  am going to do this : 

Simply replace the basic command with its holymotion version. Additionally, if I want to execute the command just once, I can directly press the first key present in the avy-keys variable.

Or

Replace the basic command with an alternative version that, depending on a variable (bind to a keystroke), allows you to execute either the basic or the holymotion version. It would look something like this:

```
    (setq my-var t)

    (defun toggle-my-var ()
      "DOCSTRING"
      (if my-var
          (setq my-var nil)
        (setq my-var t)))

    (defun holymotion-next-line-with-variable ()
      "DOCSTRING here"
      (interactive)
      (if my-var
          (holymotion-next-line)
        (next-line)))
```
And  toggle-my-var is bind to an accessible key.

The second method is a bit messy to do this for every function. Do you see another way to integrate a variable into a new macro that would allow us to do this?

Edit :  your holymotion-map is another solution that can work, but not for me ^^

**Comment by Overdr0ne** [comment]
Ah, that makes much more sense, and yes that is definitely doable. However, I would not use just a raw variable for that. This is exactly what a [minor-mode](https://www.gnu.org/software/emacs/manual/html_node/emacs/Minor-Modes.html) is designed for. Instead of having a variable internal to your function, we could use a keymap that is activated when the minor mode is activated(those keymaps are actually created by default when you create a minor mode). So you can replace your normal keybinding/s within that minor mode keymap, and activate it when you want. You also get buffer locality for free. And that is certainly a new idea, not present in the original evil-easymotion, and something I think could be pretty valuable. I'll hack something together here soon...

**Comment by Overdr0ne** [comment]
And, if you want a global version, that is also doable.

**Comment by Cletip** [comment]
Ok, I think you got it. Thank you for listening to me and taking this kind of feedback into account :) Take your time and don't put too much pressure on yourself for that ^^

**Comment by Overdr0ne** [comment]
No trouble at all Cletip, I'm happy to do it.
