### ISSUE TITLE
Propose a remap in the documentation

### ISSUE THREAD

**Issue by Cletip** [Overdr0ne/holymotion#3]
Hi, sorry again me :)
This is not a real issue, but I think it can greatly help beginners / be relevant to the package philosophy: talk about the remap feature in emacs. For example this: 
```
(define-key minibuffer-mode-map [remap previous-line] #'previous-line-or-history-element)
  (define-key minibuffer-mode-map [remap next-line] #'next-line-or-history-element)
```
is a remap.

**Comment by Overdr0ne** [comment]
I agree, remap is super powerful, and it took me too long to find it. Will do.

**Comment by Cletip** [comment]
Perfect! Close this issue whenever you want :)
